# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialo1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 101)
        Dialog.setSizeGripEnabled(False)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.second_btn = QtWidgets.QPushButton(Dialog)
        self.second_btn.setObjectName("second_btn")
        self.gridLayout.addWidget(self.second_btn, 1, 1, 1, 1)
        self.first_btn = QtWidgets.QPushButton(Dialog)
        self.first_btn.setObjectName("first_btn")
        self.gridLayout.addWidget(self.first_btn, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Найдены два блока"))
        self.second_btn.setText(_translate("Dialog", "блок2"))
        self.first_btn.setText(_translate("Dialog", "блок 1"))
        self.label.setText(_translate("Dialog", "К какому блоку подключиться?"))
