self.groupBox_4 = QtWidgets.QGroupBox(self.often_used_params)
self.groupBox_4.setEnabled(False)
self.groupBox_4.setObjectName("groupBox_4")
self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_4)
self.verticalLayout_7.setObjectName("verticalLayout_7")
self.warn_temp = QtWidgets.QGroupBox(self.groupBox_4)
self.warn_temp.setObjectName("warn_temp")
self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.warn_temp)
self.horizontalLayout_9.setObjectName("horizontalLayout_9")
self.warning_temperature = QtWidgets.QSlider(self.warn_temp)
self.warning_temperature.setMinimum(20)
self.warning_temperature.setMaximum(90)
self.warning_temperature.setOrientation(QtCore.Qt.Horizontal)
self.warning_temperature.setTickPosition(QtWidgets.QSlider.NoTicks)
self.warning_temperature.setObjectName("warning_temperature")
self.horizontalLayout_9.addWidget(self.warning_temperature)
self.lab_warning_temperature = QtWidgets.QLabel(self.warn_temp)
font = QtGui.QFont()
font.setPointSize(12)
font.setBold(True)
font.setWeight(75)
self.lab_warning_temperature.setFont(font)
self.lab_warning_temperature.setText("")
self.lab_warning_temperature.setObjectName("lab_warning_temperature")
self.horizontalLayout_9.addWidget(self.lab_warning_temperature)
self.verticalLayout_7.addWidget(self.warn_temp)
self.zone = QtWidgets.QGroupBox(self.groupBox_4)
self.gridLayout.addWidget(self.groupBox_4, 1, 1, 2, 1)
self.groupBox_4.setTitle(_translate("MainWindow", "Частые настройки"))
